/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package agpasseiocavalo.view;

import agpasseiocavalo.model.Populacao;
import agpasseiocavalo.model.Tabuleiro;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author igor
 */
public class Interface extends javax.swing.JFrame {
    
    ArrayList<JLabel> labels = new ArrayList<>();
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        setLocation(screenWidth / 4, screenHeight / 8);
        
        carregaLabels();

    }
    
    public final void carregaLabels(){
        this.labels.add(um);
        this.labels.add(dois);
        this.labels.add(tres);
        this.labels.add(quatro);
        this.labels.add(cinco);
        this.labels.add(seis);
        this.labels.add(sete);
        this.labels.add(oito);
        this.labels.add(nove);
        this.labels.add(dez);
        this.labels.add(onze);
        this.labels.add(doze);
        this.labels.add(treze);
        this.labels.add(quatorze);
        this.labels.add(quinze);
        this.labels.add(dezesseis);
        this.labels.add(dezessete);
        this.labels.add(dezoito);
        this.labels.add(dezenove);
        this.labels.add(vinte);
        this.labels.add(vinteum);
        this.labels.add(vintedois);
        this.labels.add(vintetres);
        this.labels.add(vintequatro);
        this.labels.add(vintecinco);
        this.labels.add(vinteseis);
        this.labels.add(vintesete);
        this.labels.add(vinteoito);
        this.labels.add(vintenove);
        this.labels.add(trinta);
        this.labels.add(trintaum);
        this.labels.add(trintadois);
        this.labels.add(trintatres);
        this.labels.add(trintaquatro);
        this.labels.add(trintacinco);
        this.labels.add(trintaseis);
        this.labels.add(trintasete);
        this.labels.add(trintaoito);
        this.labels.add(trintanove);
        this.labels.add(quarenta);
        this.labels.add(quarentaum);
        this.labels.add(quarentadois);
        this.labels.add(quarentatres);
        this.labels.add(quarentaquatro);
        this.labels.add(quarentacinco);
        this.labels.add(quarentaseis);
        this.labels.add(quarentasete);
        this.labels.add(quarentaoito);
        this.labels.add(quarentanove);
        this.labels.add(cinquenta);
        this.labels.add(cinquentaum);
        this.labels.add(cinquentadois);
        this.labels.add(cinquentatres);
        this.labels.add(cinquentaquatro);
        this.labels.add(cinquentacinco);
        this.labels.add(cinquentaseis);
        this.labels.add(cinquentasete);
        this.labels.add(cinquentaoito);
        this.labels.add(cinquentanove);
        this.labels.add(sessenta);
        this.labels.add(sessentaum);
        this.labels.add(sessentadois);
        this.labels.add(sessentatres);
        this.labels.add(sessentaquatro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        um = new javax.swing.JLabel();
        dois = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        quatro = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        sete = new javax.swing.JLabel();
        oito = new javax.swing.JLabel();
        nove = new javax.swing.JLabel();
        dez = new javax.swing.JLabel();
        onze = new javax.swing.JLabel();
        doze = new javax.swing.JLabel();
        treze = new javax.swing.JLabel();
        quatorze = new javax.swing.JLabel();
        quinze = new javax.swing.JLabel();
        dezesseis = new javax.swing.JLabel();
        dezessete = new javax.swing.JLabel();
        dezoito = new javax.swing.JLabel();
        dezenove = new javax.swing.JLabel();
        vinte = new javax.swing.JLabel();
        vinteum = new javax.swing.JLabel();
        vintedois = new javax.swing.JLabel();
        vintetres = new javax.swing.JLabel();
        vintequatro = new javax.swing.JLabel();
        vintecinco = new javax.swing.JLabel();
        vinteseis = new javax.swing.JLabel();
        vintesete = new javax.swing.JLabel();
        vinteoito = new javax.swing.JLabel();
        vintenove = new javax.swing.JLabel();
        trinta = new javax.swing.JLabel();
        trintaum = new javax.swing.JLabel();
        trintadois = new javax.swing.JLabel();
        trintatres = new javax.swing.JLabel();
        trintaquatro = new javax.swing.JLabel();
        trintacinco = new javax.swing.JLabel();
        trintaseis = new javax.swing.JLabel();
        trintasete = new javax.swing.JLabel();
        trintaoito = new javax.swing.JLabel();
        trintanove = new javax.swing.JLabel();
        quarenta = new javax.swing.JLabel();
        quarentaum = new javax.swing.JLabel();
        quarentadois = new javax.swing.JLabel();
        quarentatres = new javax.swing.JLabel();
        quarentaquatro = new javax.swing.JLabel();
        quarentacinco = new javax.swing.JLabel();
        quarentaseis = new javax.swing.JLabel();
        quarentasete = new javax.swing.JLabel();
        quarentaoito = new javax.swing.JLabel();
        quarentanove = new javax.swing.JLabel();
        cinquenta = new javax.swing.JLabel();
        cinquentaum = new javax.swing.JLabel();
        cinquentadois = new javax.swing.JLabel();
        cinquentatres = new javax.swing.JLabel();
        cinquentaquatro = new javax.swing.JLabel();
        cinquentacinco = new javax.swing.JLabel();
        cinquentaseis = new javax.swing.JLabel();
        cinquentasete = new javax.swing.JLabel();
        cinquentaoito = new javax.swing.JLabel();
        cinquentanove = new javax.swing.JLabel();
        sessenta = new javax.swing.JLabel();
        sessentaum = new javax.swing.JLabel();
        sessentadois = new javax.swing.JLabel();
        sessentatres = new javax.swing.JLabel();
        sessentaquatro = new javax.swing.JLabel();
        TabuleiroImagem = new javax.swing.JLabel();
        CavaloImagem = new javax.swing.JLabel();
        LabelTitulo = new javax.swing.JLabel();
        LabelPopulacao = new javax.swing.JLabel();
        TextFieldPopulacao = new javax.swing.JTextField();
        LabelGeracoes = new javax.swing.JLabel();
        TextFieldGeracoes = new javax.swing.JTextField();
        LabelX = new javax.swing.JLabel();
        TextFieldPosicaoX = new javax.swing.JTextField();
        LabelY = new javax.swing.JLabel();
        TextFieldPosicaoY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextFieldTaxaMutacao = new javax.swing.JTextField();
        ButtonOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextFieldCruzamentos = new javax.swing.JTextField();
        LabelSolucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passeio do Cavalo");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));

        um.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        um.setMinimumSize(new java.awt.Dimension(5, 5));
        um.setBounds(20, 100, 25, 25);
        jLayeredPane1.add(um, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dois.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dois.setForeground(new java.awt.Color(255, 255, 255));
        dois.setMinimumSize(new java.awt.Dimension(5, 5));
        dois.setBounds(60, 90, 25, 25);
        jLayeredPane1.add(dois, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tres.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tres.setBounds(110, 90, 25, 25);
        jLayeredPane1.add(tres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quatro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quatro.setForeground(new java.awt.Color(255, 255, 255));
        quatro.setBounds(160, 100, 25, 25);
        jLayeredPane1.add(quatro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinco.setBounds(210, 100, 25, 25);
        jLayeredPane1.add(cinco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        seis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setBounds(260, 100, 25, 25);
        jLayeredPane1.add(seis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sete.setBounds(300, 100, 25, 25);
        jLayeredPane1.add(sete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        oito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        oito.setForeground(new java.awt.Color(255, 255, 255));
        oito.setBounds(360, 100, 25, 25);
        jLayeredPane1.add(oito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nove.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        nove.setForeground(new java.awt.Color(255, 255, 255));
        nove.setBounds(20, 150, 25, 25);
        jLayeredPane1.add(nove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dez.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dez.setBounds(60, 150, 25, 25);
        jLayeredPane1.add(dez, javax.swing.JLayeredPane.DEFAULT_LAYER);

        onze.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        onze.setForeground(new java.awt.Color(255, 255, 255));
        onze.setBounds(110, 140, 25, 25);
        jLayeredPane1.add(onze, javax.swing.JLayeredPane.DEFAULT_LAYER);

        doze.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        doze.setBounds(160, 150, 25, 25);
        jLayeredPane1.add(doze, javax.swing.JLayeredPane.DEFAULT_LAYER);

        treze.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        treze.setForeground(new java.awt.Color(255, 255, 255));
        treze.setBounds(210, 140, 25, 25);
        jLayeredPane1.add(treze, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quatorze.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quatorze.setBounds(260, 150, 25, 25);
        jLayeredPane1.add(quatorze, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quinze.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quinze.setForeground(new java.awt.Color(255, 255, 255));
        quinze.setBounds(310, 150, 25, 25);
        jLayeredPane1.add(quinze, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dezesseis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dezesseis.setBounds(360, 150, 25, 25);
        jLayeredPane1.add(dezesseis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dezessete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dezessete.setBounds(20, 200, 25, 25);
        jLayeredPane1.add(dezessete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dezoito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dezoito.setForeground(new java.awt.Color(255, 255, 255));
        dezoito.setBounds(70, 200, 25, 25);
        jLayeredPane1.add(dezoito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dezenove.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        dezenove.setBounds(110, 190, 25, 25);
        jLayeredPane1.add(dezenove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vinte.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vinte.setForeground(new java.awt.Color(255, 255, 255));
        vinte.setBounds(160, 190, 25, 25);
        jLayeredPane1.add(vinte, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vinteum.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vinteum.setBounds(210, 200, 25, 25);
        jLayeredPane1.add(vinteum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vintedois.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vintedois.setForeground(new java.awt.Color(255, 255, 255));
        vintedois.setBounds(260, 190, 25, 25);
        jLayeredPane1.add(vintedois, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vintetres.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vintetres.setBounds(310, 190, 25, 25);
        jLayeredPane1.add(vintetres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vintequatro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vintequatro.setForeground(new java.awt.Color(255, 255, 255));
        vintequatro.setBounds(360, 190, 25, 25);
        jLayeredPane1.add(vintequatro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vintecinco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vintecinco.setForeground(new java.awt.Color(255, 255, 255));
        vintecinco.setBounds(10, 237, 25, 25);
        jLayeredPane1.add(vintecinco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vinteseis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vinteseis.setBounds(60, 240, 25, 25);
        jLayeredPane1.add(vinteseis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vintesete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vintesete.setForeground(new java.awt.Color(255, 255, 255));
        vintesete.setBounds(120, 240, 25, 25);
        jLayeredPane1.add(vintesete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vinteoito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vinteoito.setBounds(160, 240, 25, 25);
        jLayeredPane1.add(vinteoito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vintenove.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        vintenove.setForeground(new java.awt.Color(255, 255, 255));
        vintenove.setBounds(210, 240, 25, 25);
        jLayeredPane1.add(vintenove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trinta.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trinta.setBounds(260, 240, 25, 25);
        jLayeredPane1.add(trinta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintaum.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintaum.setForeground(new java.awt.Color(255, 255, 255));
        trintaum.setBounds(310, 240, 25, 25);
        jLayeredPane1.add(trintaum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintadois.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintadois.setBounds(360, 240, 25, 25);
        jLayeredPane1.add(trintadois, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintatres.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintatres.setBounds(20, 290, 25, 25);
        jLayeredPane1.add(trintatres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintaquatro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintaquatro.setForeground(new java.awt.Color(255, 255, 255));
        trintaquatro.setBounds(60, 290, 25, 25);
        jLayeredPane1.add(trintaquatro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintacinco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintacinco.setBounds(120, 290, 25, 25);
        jLayeredPane1.add(trintacinco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintaseis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintaseis.setForeground(new java.awt.Color(255, 255, 255));
        trintaseis.setBounds(160, 290, 25, 25);
        jLayeredPane1.add(trintaseis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintasete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintasete.setBounds(210, 290, 25, 25);
        jLayeredPane1.add(trintasete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintaoito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintaoito.setForeground(new java.awt.Color(255, 255, 255));
        trintaoito.setBounds(260, 290, 25, 25);
        jLayeredPane1.add(trintaoito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trintanove.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        trintanove.setBounds(310, 290, 25, 25);
        jLayeredPane1.add(trintanove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarenta.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarenta.setForeground(new java.awt.Color(255, 255, 255));
        quarenta.setBounds(360, 290, 25, 25);
        jLayeredPane1.add(quarenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentaum.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentaum.setForeground(new java.awt.Color(255, 255, 255));
        quarentaum.setBounds(10, 340, 25, 25);
        jLayeredPane1.add(quarentaum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentadois.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentadois.setBounds(60, 340, 25, 25);
        jLayeredPane1.add(quarentadois, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentatres.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentatres.setForeground(new java.awt.Color(255, 255, 255));
        quarentatres.setBounds(110, 340, 25, 25);
        jLayeredPane1.add(quarentatres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentaquatro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentaquatro.setBounds(160, 340, 25, 25);
        jLayeredPane1.add(quarentaquatro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentacinco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentacinco.setForeground(new java.awt.Color(255, 255, 255));
        quarentacinco.setBounds(210, 340, 25, 25);
        jLayeredPane1.add(quarentacinco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentaseis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentaseis.setBounds(260, 340, 25, 25);
        jLayeredPane1.add(quarentaseis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentasete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentasete.setForeground(new java.awt.Color(255, 255, 255));
        quarentasete.setBounds(310, 340, 25, 25);
        jLayeredPane1.add(quarentasete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentaoito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentaoito.setBounds(360, 340, 25, 25);
        jLayeredPane1.add(quarentaoito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quarentanove.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quarentanove.setBounds(20, 390, 25, 25);
        jLayeredPane1.add(quarentanove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquenta.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquenta.setForeground(new java.awt.Color(255, 255, 255));
        cinquenta.setBounds(70, 390, 25, 25);
        jLayeredPane1.add(cinquenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentaum.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentaum.setBounds(110, 390, 25, 25);
        jLayeredPane1.add(cinquentaum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentadois.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentadois.setForeground(new java.awt.Color(255, 255, 255));
        cinquentadois.setBounds(170, 390, 25, 25);
        jLayeredPane1.add(cinquentadois, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentatres.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentatres.setBounds(210, 390, 25, 25);
        jLayeredPane1.add(cinquentatres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentaquatro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentaquatro.setForeground(new java.awt.Color(255, 255, 255));
        cinquentaquatro.setBounds(260, 390, 25, 25);
        jLayeredPane1.add(cinquentaquatro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentacinco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentacinco.setBounds(310, 390, 25, 25);
        jLayeredPane1.add(cinquentacinco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentaseis.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentaseis.setForeground(new java.awt.Color(255, 255, 255));
        cinquentaseis.setBounds(360, 390, 25, 25);
        jLayeredPane1.add(cinquentaseis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentasete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentasete.setForeground(new java.awt.Color(255, 255, 255));
        cinquentasete.setBounds(10, 440, 25, 25);
        jLayeredPane1.add(cinquentasete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentaoito.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentaoito.setBounds(70, 440, 25, 25);
        jLayeredPane1.add(cinquentaoito, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cinquentanove.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cinquentanove.setForeground(new java.awt.Color(255, 255, 255));
        cinquentanove.setBounds(110, 440, 25, 25);
        jLayeredPane1.add(cinquentanove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sessenta.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sessenta.setBounds(160, 440, 25, 25);
        jLayeredPane1.add(sessenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sessentaum.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sessentaum.setForeground(new java.awt.Color(255, 255, 255));
        sessentaum.setBounds(210, 440, 25, 25);
        jLayeredPane1.add(sessentaum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sessentadois.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sessentadois.setBounds(260, 440, 25, 25);
        jLayeredPane1.add(sessentadois, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sessentatres.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sessentatres.setForeground(new java.awt.Color(255, 255, 255));
        sessentatres.setBounds(310, 440, 25, 25);
        jLayeredPane1.add(sessentatres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sessentaquatro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sessentaquatro.setBounds(350, 430, 25, 25);
        jLayeredPane1.add(sessentaquatro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TabuleiroImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agpasseiocavalo/files/Tabuleiro2.jpg"))); // NOI18N
        TabuleiroImagem.setBounds(0, 80, 430, 400);
        jLayeredPane1.add(TabuleiroImagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CavaloImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agpasseiocavalo/files/cavalo3.png"))); // NOI18N
        CavaloImagem.setBounds(500, 30, 100, 180);
        jLayeredPane1.add(CavaloImagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelTitulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        LabelTitulo.setText("Passeio do Cavalo");
        LabelTitulo.setBounds(220, 10, 220, 60);
        jLayeredPane1.add(LabelTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelPopulacao.setText("Populacao: ");
        LabelPopulacao.setBounds(410, 290, 90, 30);
        jLayeredPane1.add(LabelPopulacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TextFieldPopulacao.setText("1000");
        TextFieldPopulacao.setBounds(520, 290, 50, 27);
        jLayeredPane1.add(TextFieldPopulacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelGeracoes.setText("Gerações:");
        LabelGeracoes.setBounds(410, 320, 80, 30);
        jLayeredPane1.add(LabelGeracoes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TextFieldGeracoes.setText("1000");
        TextFieldGeracoes.setBounds(520, 320, 50, 27);
        jLayeredPane1.add(TextFieldGeracoes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelX.setText("Posição X:");
        LabelX.setBounds(410, 230, 80, 30);
        jLayeredPane1.add(LabelX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TextFieldPosicaoX.setText("4");
        TextFieldPosicaoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPosicaoXActionPerformed(evt);
            }
        });
        TextFieldPosicaoX.setBounds(490, 230, 30, 27);
        jLayeredPane1.add(TextFieldPosicaoX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelY.setText("Posição Y:");
        LabelY.setBounds(530, 227, 80, 30);
        jLayeredPane1.add(LabelY, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TextFieldPosicaoY.setText("4");
        TextFieldPosicaoY.setBounds(610, 230, 30, 27);
        jLayeredPane1.add(TextFieldPosicaoY, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Taxa Mutação:");
        jLabel1.setBounds(410, 380, 110, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TextFieldTaxaMutacao.setText("10");
        TextFieldTaxaMutacao.setBounds(520, 380, 50, 27);
        jLayeredPane1.add(TextFieldTaxaMutacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ButtonOK.setText("OK");
        ButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOKActionPerformed(evt);
            }
        });
        ButtonOK.setBounds(586, 420, 70, 29);
        jLayeredPane1.add(ButtonOK, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Cruzamentos:");
        jLabel2.setBounds(410, 347, 110, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TextFieldCruzamentos.setText("100");
        TextFieldCruzamentos.setBounds(520, 350, 50, 27);
        jLayeredPane1.add(TextFieldCruzamentos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LabelSolucao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LabelSolucao.setForeground(new java.awt.Color(255, 0, 0));
        LabelSolucao.setBounds(420, 440, 150, 30);
        jLayeredPane1.add(LabelSolucao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldPosicaoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPosicaoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPosicaoXActionPerformed

    private void ButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOKActionPerformed
        Populacao populacao;
        Tabuleiro tabuleiro = new Tabuleiro();
        
        int tam = (int) Integer.parseInt(this.TextFieldPopulacao.getText());
        int numGeracoes = (int) Integer.parseInt(this.TextFieldGeracoes.getText());
        int cruzamentos = (int) Integer.parseInt(this.TextFieldCruzamentos.getText());
        
        populacao = new Populacao(tam,cruzamentos);
        
        populacao.setTaxaMutacao((int) Integer.parseInt(this.TextFieldTaxaMutacao.getText()));
        
        tabuleiro.setPosicaoXCavalo(((int) Integer.parseInt(this.TextFieldPosicaoX.getText())) -1);
        tabuleiro.setPosicaoXInicial(((int) Integer.parseInt(this.TextFieldPosicaoX.getText())) -1);
        tabuleiro.setPosicaoYCavalo(((int) Integer.parseInt(this.TextFieldPosicaoY.getText())) -1);
        tabuleiro.setPosicaoYInicial(((int) Integer.parseInt(this.TextFieldPosicaoY.getText())) -1);
        
        int inicial = mapeia(tabuleiro.getPosicaoXCavalo(),tabuleiro.getPosicaoYCavalo());
        
        ImageIcon imagem = new ImageIcon("/home/igor/NetBeansProjects/AGPasseioCavalo/src/agpasseiocavalo/files/cavalo4.png"); 
        this.labels.get(inicial).setIcon(imagem);
        this.labels.get(inicial).repaint();
        
        populacao.inicializarPopulacao();
        
        populacao.calculaAptidao(populacao.getPopulacao(),tabuleiro.getPosicaoXCavalo(), tabuleiro.getPosicaoYCavalo());
        
        while(numGeracoes > 0){
            populacao.cruzamento();
            populacao.mutacao();
            populacao.calculaAptidao(populacao.getFilhos(), tabuleiro.getPosicaoXCavalo(), tabuleiro.getPosicaoYCavalo());
            populacao.selecao();
            --numGeracoes;
            
            // aumentando a variabilidade genetica
//            for(int i= (int) (tam*0.1); i > 0; i--){
//                populacao.getPopulacao()[i].geraGenesAleatorio();
//            }
            
        }
        
        JOptionPane.showMessageDialog(null, "Melhor Solucao: " + populacao.getPopulacao()[0].getAptidao(), "Solução", 1);
        
        this.LabelSolucao.setText("Solucao: " + populacao.getPopulacao()[0].getAptidao());
        
        int i = 0;
        int posicaoX = tabuleiro.getPosicaoXCavalo();
        int posicaoY = tabuleiro.getPosicaoYCavalo();
        int mov;
        
        while(i < populacao.getPopulacao()[0].getAptidao()){
            mov = populacao.getPopulacao()[0].getGenes()[i];
            if (mov == 0) {
                    posicaoX += agpasseiocavalo.model.Enum.ZERO.getX();
                    posicaoY += agpasseiocavalo.model.Enum.ZERO.getY();
                } else if (mov == 1) {
                    posicaoX += agpasseiocavalo.model.Enum.UM.getX();
                    posicaoY += agpasseiocavalo.model.Enum.UM.getY();
                } else if (mov == 2) {
                    posicaoX += agpasseiocavalo.model.Enum.DOIS.getX();
                    posicaoY += agpasseiocavalo.model.Enum.DOIS.getY();
                } else if (mov == 3) {
                    posicaoX += agpasseiocavalo.model.Enum.TRES.getX();
                    posicaoY += agpasseiocavalo.model.Enum.TRES.getY();
                } else if (mov == 4) {
                    posicaoX += agpasseiocavalo.model.Enum.QUATRO.getX();
                    posicaoY += agpasseiocavalo.model.Enum.QUATRO.getY();
                } else if (mov == 5) {
                    posicaoX += agpasseiocavalo.model.Enum.CINTO.getX();
                    posicaoY += agpasseiocavalo.model.Enum.CINTO.getY();
                } else if (mov == 6) {
                    posicaoX += agpasseiocavalo.model.Enum.SEIS.getX();
                    posicaoY += agpasseiocavalo.model.Enum.SEIS.getY();
                } else if (mov == 7) {
                    posicaoX += agpasseiocavalo.model.Enum.SETE.getX();
                    posicaoY += agpasseiocavalo.model.Enum.SETE.getY();
                }
            plot(mapeia(posicaoX,posicaoY),i);
            //plot(i,mov);
            ++i;
        }
        
    }//GEN-LAST:event_ButtonOKActionPerformed

    public void plot(int posicao, int mov){
        int aux = posicao;
        
        this.labels.get(aux).setText(String.valueOf(mov+1));
    }
    
    public int mapeia(int x, int y){
        int cont = 0;
        while(x > 0){
            ++cont;
            --x;
        }
        while(y > 0){
            cont += 8;
            --y;
        }
        return cont;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOK;
    private javax.swing.JLabel CavaloImagem;
    private javax.swing.JLabel LabelGeracoes;
    private javax.swing.JLabel LabelPopulacao;
    private javax.swing.JLabel LabelSolucao;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelX;
    private javax.swing.JLabel LabelY;
    private javax.swing.JLabel TabuleiroImagem;
    private javax.swing.JTextField TextFieldCruzamentos;
    private javax.swing.JTextField TextFieldGeracoes;
    private javax.swing.JTextField TextFieldPopulacao;
    private javax.swing.JTextField TextFieldPosicaoX;
    private javax.swing.JTextField TextFieldPosicaoY;
    private javax.swing.JTextField TextFieldTaxaMutacao;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cinquenta;
    private javax.swing.JLabel cinquentacinco;
    private javax.swing.JLabel cinquentadois;
    private javax.swing.JLabel cinquentanove;
    private javax.swing.JLabel cinquentaoito;
    private javax.swing.JLabel cinquentaquatro;
    private javax.swing.JLabel cinquentaseis;
    private javax.swing.JLabel cinquentasete;
    private javax.swing.JLabel cinquentatres;
    private javax.swing.JLabel cinquentaum;
    private javax.swing.JLabel dez;
    private javax.swing.JLabel dezenove;
    private javax.swing.JLabel dezesseis;
    private javax.swing.JLabel dezessete;
    private javax.swing.JLabel dezoito;
    private javax.swing.JLabel dois;
    private javax.swing.JLabel doze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nove;
    private javax.swing.JLabel oito;
    private javax.swing.JLabel onze;
    private javax.swing.JLabel quarenta;
    private javax.swing.JLabel quarentacinco;
    private javax.swing.JLabel quarentadois;
    private javax.swing.JLabel quarentanove;
    private javax.swing.JLabel quarentaoito;
    private javax.swing.JLabel quarentaquatro;
    private javax.swing.JLabel quarentaseis;
    private javax.swing.JLabel quarentasete;
    private javax.swing.JLabel quarentatres;
    private javax.swing.JLabel quarentaum;
    private javax.swing.JLabel quatorze;
    private javax.swing.JLabel quatro;
    private javax.swing.JLabel quinze;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel sessenta;
    private javax.swing.JLabel sessentadois;
    private javax.swing.JLabel sessentaquatro;
    private javax.swing.JLabel sessentatres;
    private javax.swing.JLabel sessentaum;
    private javax.swing.JLabel sete;
    private javax.swing.JLabel tres;
    private javax.swing.JLabel treze;
    private javax.swing.JLabel trinta;
    private javax.swing.JLabel trintacinco;
    private javax.swing.JLabel trintadois;
    private javax.swing.JLabel trintanove;
    private javax.swing.JLabel trintaoito;
    private javax.swing.JLabel trintaquatro;
    private javax.swing.JLabel trintaseis;
    private javax.swing.JLabel trintasete;
    private javax.swing.JLabel trintatres;
    private javax.swing.JLabel trintaum;
    private javax.swing.JLabel um;
    private javax.swing.JLabel vinte;
    private javax.swing.JLabel vintecinco;
    private javax.swing.JLabel vintedois;
    private javax.swing.JLabel vintenove;
    private javax.swing.JLabel vinteoito;
    private javax.swing.JLabel vintequatro;
    private javax.swing.JLabel vinteseis;
    private javax.swing.JLabel vintesete;
    private javax.swing.JLabel vintetres;
    private javax.swing.JLabel vinteum;
    // End of variables declaration//GEN-END:variables
}
